#.travis.yml

language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master

before_script:
  - npm i -g @angular/cli@latest
  - npm i -g angular-cli-ghpages

script:
  - npm run build
  - npm run copy:cname

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: dist/DubPlus-Site
  on:
    branch: master

notifications:
  email:
    on_failure: change
    on_success: change
